context:
  name: scippnexus
  version: "25.6.0"
  python_min: "3.10"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/scippnexus-${{ version }}.tar.gz
  sha256: cd828cd3e26c57273c329d8a536953ff38e3b99311de1411fe6fb13a3e74fd92

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=68
    - setuptools-scm >=8.0
    - pip
  run:
    - python >=${{ python_min }}
    - python-dateutil
    - scipp >=24.02.0
    - scipy
    - h5py

tests:
  - python:
      imports:
        - scippnexus
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  homepage: https://scipp.github.io/scippnexus/
  summary: An h5py-like utility for NeXus files with seamless Scipp integration
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MridulS
    - conda-forge/scipp
